### ISSUE TITLE
ES adapter Hits Mode issue

### ISSUE THREAD

**Issue by pavel-stros** [WedjaaOpen/ElasticJasper#2]
There is an issue with the "Hits Mode". 

 Independent of the "required" query, for example
 {
   "query":  { "match": { "@msgHost": "ALFA" }},
   size: 3
 }

 additional (hardcoded?) query or even queries
 {"from":0,"size":100}
 {"from":100,"size":100}
 ...

 
are executed in Elasticsearch and both the preview and report are created from the results of these additional queries, surprisingly trimmed to the required count of records (3 in the example above).

As a result, it is not possible to query specific "matching" records from the Elasticsearch database within the "Hits Mode", because the oldest unfiltered records are always presented by the plugin from Elasticsearch.

**Comment by Wedjaa** [comment]
Found the issue. It was a bug due to the behaviour of setting 'size' and 'from' when creating a query. When you set a size in the SearchBuilder it will overwrite the query. Worked on a fix, committing it now in the main branch, will have to port it to the 0.5.0 branch.
